export const ProductsData = [
  
  

  {
    name: "Luxury Handbag",
    description:
      "This leather handbag is perfect for the fashion-conscious woman on the go. Made with high-quality materials, it features a spacious interior, multiple compartments, and an adjustable strap for added comfort.",
    price: 200,
    priceLarge: 120,
    priceSmall: 300,
    size: ["medium", "large", "small"],
    brand: "Designer Brand",
    color: "Black",
    discount: 0.1,
    cart: 1,
    availableCities: ["Delhi", "Mumbai", "Chennai"],
  },



  {
    Name: "Fitness Yoga Mat",
    description:
      "This high-density yoga mat is perfect for your yoga practice. It provides a comfortable, non-slip surface for a safe and stable experience.",
    price: 200,
    priceLarge: 120,
    priceSmall: 300,
    size: ["medium", "large", "small"],
    Brand: "Fitness Brand",
    Color: "Purple",
    Discount: 0.5,
    Cart: 1,
    availableCities: ["Delhi", "Mumbai", " Chennai", " Kolkata"],
  },

  {
    name: "Designer Sunglasses",
    description:
      "These designer sunglasses are perfect for the fashion-conscious person on the go. Made with high-quality materials and UV protection, they feature a sleek and stylish design. Available in multiple colors.",
    price: 150,
    priceLarge: 200,
    priceSmall: 100,
    size: ["medium", "large", "small"],
    brand: "Luxury Brand",
    color: "Black",
    discount: 0.2,
    cart: 2,
    availableCities: ["New York", "Los Angeles", "Chicago"],
  },
  {
    name: "Designer Watch",
    description:
      "This designer watch is perfect for the fashion-conscious person on the go. Made with high-quality materials, it features a sleek and stylish design with multiple functions such as chronograph and water resistant. Available in multiple colors.",
    price: 350,
    priceLarge: 450,
    priceSmall: 300,
    size: ["medium", "large", "small"],
    brand: "Luxury Brand",
    color: "Silver",
    discount: 0.1,
    cart: 3,
    availableCities: ["Paris", "Dubai", "Hong Kong"],
  },

  {
    name: "Luxury Sneakers",
    description:
      "These luxury sneakers are perfect for the fashion-conscious person on the go. Made with high-quality materials and comfortable design, they feature a sleek and stylish design. Available in multiple colors.",
    price: 250,
    priceLarge: 300,
    priceSmall: 200,
    size: ["medium", "large", "small"],
    brand: "Designer Brand",
    color: "White",
    discount: 0.15,
    cart: 1,
    availableCities: ["London", "Barcelona", "Sydney"],
  },
  {
    name: "Designer Jewelry",
    description:
      "This designer jewelry is perfect for the fashion-conscious person on the go. Made with high-quality materials, it features a sleek and stylish design. Available in multiple colors.",
    price: 100,
    priceLarge: 150,
    priceSmall: 50,
    size: ["medium", "large", "small"],
    brand: "Luxury Brand",
    color: "Gold",
    discount: 0.1,
    cart: 2,
    availableCities: ["Tokyo", "Shanghai", "Moscow"],
  },
  {
    name: "Designer Perfume",
    description:
      "This designer perfume is perfect for the fashion-conscious person on the go. Made with high-quality ingredients and long lasting fragrance, it features a sleek and stylish design. Available in multiple scents.",
    price: 80,
    priceLarge: 120,
    priceSmall: 50,
    size: ["medium", "large", "small"],
    brand: "Luxury Brand",
    color: "Transparent",
    discount: 0.05,
    cart: 2,
    availableCities: ["New York", "Los Angeles", "Chicago"],
  },
  {
    name: "Designer Wallet",
    description:
      "This designer wallet is perfect for the fashion-conscious person on the go. Made with high-quality leather, it features a spacious interior, multiple compartments, and an RFID blocking technology for added security. Available in multiple colors.",
    price: 75,
    priceLarge: 90,
    priceSmall: 50,
    size: ["medium", "large", "small"],
    brand: "Luxury Brand",
    color: "Brown",
    discount: 0.1,
    cart: 1,
    availableCities: ["San Francisco", "Houston", "Toronto"],
    
  },
  {
    name: "Designer Backpack",
    description: "This designer backpack is perfect for the fashion-conscious person on the go. Made with high-quality materials, it features a spacious interior, multiple compartments, and a comfortable design. Available in multiple colors.",
    price: 90,
    priceLarge:120,
    priceSmall:60,
    size: ["medium", "large","small"],
    brand: "Luxury Brand",
    color: "Blue",
    discount: 0.1,
    cart: 2,
    availableCities: ["Seattle", "Denver", "Boston"],
    },
    
    {
    name: "Designer Scarf",
    description: "This designer scarf is perfect for the fashion-conscious person on the go. Made with high-quality materials, it features a sleek and stylish design and available in multiple colors.",
    price: 50,
    priceLarge:70,
    priceSmall:30,
    size: ["medium", "large","small"],
    brand: "Designer Brand",
    color: "Gray",
    discount: 0.1,
    cart: 1,
    availableCities: ["Miami", "Phoenix", "Minneapolis"],
    },
    {
      name: "Designer T-Shirt",
      description: "This designer t-shirt is perfect for the fashion-conscious person on the go. Made with high-quality materials, it features a comfortable and stylish design and available in multiple colors and sizes",
      price: 35,
      priceLarge:40,
      priceSmall:30,
      size: ["medium", "large","small","extra-large"],
      brand: "Luxury Brand",
      color: "Black",
      discount: 0.05,
      cart: 2,
      availableCities: ["New Orleans", "Pittsburgh", "San Diego"],
      },
      {
        name: "Designer Jacket",
        description: "This designer jacket is perfect for the fashion-conscious person on the go. Made with high-quality materials, it features a comfortable and stylish design and available in multiple colors and sizes. It also has water resistant feature",
        price: 150,
        priceLarge:180,
        priceSmall:120,
        size: ["medium", "large","small"],
        brand: "Luxury Brand",
        color: "Green",
        discount: 0.1,
        cart: 2,
        availableCities: ["Vancouver", "Montreal", "Ottawa"],
        },
       

{
name: "Designer Sunglasses",
description: "These designer sunglasses are perfect for the fashion-conscious person on the go. Made with high-quality materials, they feature a sleek and stylish design and available in multiple colors and lens options.",
price: 80,
priceLarge:90,
priceSmall:70,
size: ["medium", "large","small"],
brand: "Luxury Brand",
color: "Black",
discount: 0.05,
cart: 1,
availableCities: ["Los Angeles", "New York", "Chicago"],
}
,
{
name: "Designer Watch",
description: "This designer watch is perfect for the fashion-conscious person on the go. Made with high-quality materials and features a sleek and stylish design, it is available in multiple colors and has multiple functions such as stopwatch and alarm.",
price: 150,
priceLarge:200,
priceSmall:100,
size: ["medium", "large","small"],
brand: "Designer Brand",
color: "Gold",
discount: 0.1,
cart: 2,
availableCities: ["London", "Paris", "Rome"],
},
      
      {
      name: "Designer Shoes",
      description: "These designer shoes are perfect for the fashion-conscious person on the go. Made with high-quality materials and comfortable design, they feature a sleek and stylish design and available in multiple colors and sizes.",
      price: 120,
      priceLarge:150,
      priceSmall:90,
      size: ["medium", "large","small",],
      brand: "Designer Brand",
      color: "Red",
      discount: 0.1,
      cart: 1,
      availableCities: ["Houston", "Baltimore", "Portland"],
      }
];
